name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run security checks
      run: |
        pip install safety
        safety check

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/bitnami/indusnew
          git pull origin main
          sudo systemctl restart indusfashion
          sudo systemctl restart nginx

    - name: Wait for deployment to stabilize
      run: sleep 60

    - name: Health Check
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" https://www.indusfashions.org)
        if [ "$response" != "200" ]; then
          echo "Deployment health check failed! Site returned HTTP $response"
          exit 1
        else
          echo "Deployment successful! Site is responding with HTTP 200"
        fi
